import { Vocablo } from './types';

export const ARCHIVO_VIVO: Vocablo[] = [
  // ── Vocablos originales ──
  { id: 1, vocablo: 'Airapí', fonetica: 'ai-ra-pi', significado: 'Nombre original de la bahía de La Paz. Lugar de importancia espiritual y geográfica para la nación huchití.' },
  { id: 2, vocablo: 'Huaha', fonetica: 'hua-ha', significado: 'Mezquite (Prosopis articulata). Árbol fundamental para la alimentación (vainas) y tecnología (madera).' },
  { id: 3, vocablo: 'Tipanatemba', fonetica: 'ti-pa-na-tem-ba', significado: 'Neologismo para internet o red digital. Literalmente: "La red de la tierra" o "El tejido del mundo".' },
  { id: 4, vocablo: 'Apaté', fonetica: 'a-pa-te', significado: 'Marcador de no hostilidad. Traducido históricamente como "amigo" o saludo de paz.' },
  { id: 5, vocablo: 'Tammia', fonetica: 'tam-mia', significado: 'Pitahaya dulce. Eje de las reuniones sociales y ciclos migratorios estacionales.' },
  { id: 6, vocablo: 'Tiyeichapureve', fonetica: 'ti-yei-cha-pu-re-ve', significado: 'Neologismo para teléfono. Literalmente: "La voz que proviene de la distancia".' },
  { id: 7, vocablo: 'Yenecamú', fonetica: 'ye-ne-ca-mu', significado: 'Nombre original de Cabo San Lucas. Significa "Lugar donde habita la divinidad".' },
  { id: 8, vocablo: 'Ambujakeriri', fonetica: 'am-bu-ja-ke-ri-ri', significado: 'Neologismo para escuela o academia. Literalmente: "La casa del saber" o "Lugar de la cognición".' },
  { id: 9, vocablo: 'Marinó', fonetica: 'ma-ri-no', significado: 'Nombre indígena de la sierra de Santa Ana. Parte del paisaje sagrado huchití.' },
  { id: 10, vocablo: 'Kada', fonetica: 'ka-da', significado: 'Carrizo. Material esencial para la cestería, techumbres y construcción de refugios.' },

  // ── Vocablos del Corpus Documental (Zamponi 2004, Baegert 1751-1768) ──
  { id: 11, vocablo: 'Datembà', fonetica: 'da-tem-ba', significado: 'La tierra, el territorio matriz. Plataforma del nomadismo: los individuos pertenecen a datembà, no al revés.' },
  { id: 12, vocablo: 'Tekerakadatemba', fonetica: 'te-ke-ra-ka-da-tem-ba', significado: 'El cielo. Composición polisintética: tekereká (arqueado) + datembà (tierra). "La tierra arqueada sobre nuestras cabezas".' },
  { id: 13, vocablo: 'Ambía', fonetica: 'am-bi-a', significado: 'Pitahaya dulce Y un año completo. El tiempo nace cuando fructifica el cactus en las faldas de la Sierra.' },
  { id: 14, vocablo: 'Umutù', fonetica: 'u-mu-tu', significado: 'Recordar, traer al presente. Plural: kumutú = "nosotros recordamos". Esencia de la transmisión oral y del proyecto Huchití OS.' },
  { id: 15, vocablo: 'Tiyeicha', fonetica: 'ti-yei-cha', significado: 'Poder hablar, emitir la palabra codificada. Los decretos coloniales de 1795 intentaron borrar este acto de los cuerpos.' },
  { id: 16, vocablo: 'Kuitscharrakè', fonetica: 'kuit-scha-rra-ke', significado: 'Perdonar, restaurar el vínculo roto. Mecanismo interno de resolución de conflictos sin letalidad permanente.' },
  { id: 17, vocablo: 'Atacá', fonetica: 'a-ta-ka', significado: 'Lo bueno, lo favorable. No postulados dogmáticos: una cacería exitosa, una tinaja desbordante, la reciprocidad cumplida.' },
  { id: 18, vocablo: 'Vâra', fonetica: 'va-ra', significado: 'No, nada, el vacío absoluto. Lo que el sistema misional jesuita quiso hacer de la ontología huchití. El proyecto nace como negación de vâra.' },
  { id: 19, vocablo: 'Éte', fonetica: 'e-te', significado: 'Hombre, ser humano. Plural irregular: ti. Reliquia de alta antigüedad morfológica dentro de la filogenia pre-yuma.' },
  { id: 20, vocablo: 'Ánaï', fonetica: 'a-nai', significado: 'Mujer. Plural: kánaï (prefijo k-). Sostenía la arquitectura económica de la banda mediante recolección especializada.' },
  { id: 21, vocablo: 'Katé', fonetica: 'ka-te', significado: 'Nosotros (sujeto). No la suma de varios "yos" — la proclamación de la banda como entidad biológica unificada.' },
  { id: 22, vocablo: 'Aëna', fonetica: 'a-e-na', significado: 'Arriba, el cenit. Dirección de los Grandes Murales en la Sierra de la Laguna y del vuelo de las águilas.' },
  { id: 23, vocablo: 'Untâiri', fonetica: 'un-tai-ri', significado: 'Día, ciclo solar. Victoria diaria sobre la incertidumbre de la noche en los cañones serranos.' },
  { id: 24, vocablo: 'Maniká', fonetica: 'ma-ni-ka', significado: 'Pigmento ocre férrico. "La sangre de la memoria": rojo inmarcesible extraído de vetas volcánicas para los Grandes Murales.' },

  // ── Glosario Expandido (De El Uchití.md) ──
  { id: 25, vocablo: 'Rutau', fonetica: 'ru-tau', significado: 'Pronombre personal: Él.' },
  { id: 26, vocablo: 'Pete', fonetica: 'pe-te', significado: 'Pronombre personal: Ustedes.' },
  { id: 27, vocablo: 'Tucáva', fonetica: 'tu-ca-va', significado: 'Ellos, ella, o "el mismo". Marcador de identidad de grupo.' },
  { id: 28, vocablo: 'Bedáre', fonetica: 'be-da-re', significado: 'Mi padre o ancestro masculino directo.' },
  { id: 29, vocablo: 'Bécue', fonetica: 'be-cue', significado: 'Mi madre o ancestro femenino directo.' },
  { id: 30, vocablo: 'Betshánu', fonetica: 'bet-sha-nu', significado: 'Mi hijo / descendiente.' },
  { id: 31, vocablo: 'Mapá', fonetica: 'ma-pa', significado: 'Mi frente. Regla: sustantivos de cuerpo requieren posesivo simepre.' },
  { id: 32, vocablo: 'Minamú', fonetica: 'mi-na-mu', significado: 'Mi nariz.' },
  { id: 33, vocablo: 'Mituketá', fonetica: 'mi-tu-ke-ta', significado: 'Mi mano.' },
  { id: 34, vocablo: 'Mundiri', fonetica: 'mun-di-ri', significado: 'Mi brazo.' },
  { id: 35, vocablo: 'Menembeû', fonetica: 'me-nem-be-u', significado: 'Mi dolor. Nota: raíz nembeú (dolor) también requiere posesivo.' },
  { id: 36, vocablo: 'Betanía', fonetica: 'be-ta-nia', significado: 'Mi palabra. Del raíz tanía (palabra).' },
  { id: 37, vocablo: 'Amukiri', fonetica: 'a-mu-ki-ri', significado: 'Verbo: Jugar o participar en ritos lúdicos.' },
  { id: 38, vocablo: 'Akatuiké', fonetica: 'a-ka-tui-ke', significado: 'Verbo: Conocer, reconocer la esencia de algo.' },
  { id: 39, vocablo: 'Cuvu', fonetica: 'cu-vu', significado: 'Verbo: Querer, desear, tener voluntad.' },
  { id: 40, vocablo: 'Hibitsche', fonetica: 'hi-bit-sche', significado: 'Verbo: Sufrir, proceso de transformación a través del dolor.' },
  { id: 41, vocablo: 'Jebarrake', fonetica: 'je-ba-rra-ke', significado: 'Verbo: Obedecer, seguir los ciclos naturales.' },
  { id: 42, vocablo: 'Kukanja', fonetica: 'ku-kan-ja', significado: 'Verbo: Proteger, resguardar el territorio o la memoria.' },
  { id: 43, vocablo: 'Kumbáte', fonetica: 'kum-ba-te', significado: 'Verbo: Odiar, rechazar lo deletéreo para la banda.' },
  { id: 44, vocablo: 'Piabaké', fonetica: 'pia-ba-ke', significado: 'Verbo: Reñir, confrontación dialéctica o física.' },
  { id: 45, vocablo: 'Tikakambá', fonetica: 'ti-ka-kam-ba', significado: 'Verbo: Ayudar, cooperar simbióticamente.' },
  { id: 46, vocablo: 'Tschakárrake', fonetica: 'tscha-ka-rra-ke', significado: 'Verbo: Alabar, reconocer la grandeza de datembà.' },
  { id: 47, vocablo: 'Tschumuge', fonetica: 'tschum-u-ge', significado: 'Verbo: Besar, gesto de unión física.' },
  { id: 48, vocablo: 'Tshípake', fonetica: 'tshi-pa-ke', significado: 'Verbo: Golpear, marcar el ritmo o la piedra.' },
  { id: 49, vocablo: 'Ureti', fonetica: 'u-re-ti', significado: 'Verbo: Hacer, crear con las manos y la voluntad.' },
  { id: 50, vocablo: 'Apánne', fonetica: 'a-pan-ne', significado: 'Adjetivo: Grande, inabarcable.' },
  { id: 51, vocablo: 'Pari', fonetica: 'pa-ri', significado: 'Adjetivo/Adverbio: Mucho, abundancia.' },
  { id: 52, vocablo: 'Jaûpe', fonetica: 'jau-pe', significado: 'Adverbio: Aquí, en este punto geográfico exacto.' },
  { id: 53, vocablo: 'Enjéme', fonetica: 'en-je-me', significado: 'Conjunción: Entonces, marcador de secuencia temporal.' },
  { id: 54, vocablo: 'Guamongo', fonetica: 'gua-mon-go', significado: 'Entidad: Espíritu del norte, el gran creador en la mitología huchití.' },
  { id: 55, vocablo: 'Emma', fonetica: 'em-ma', significado: 'Entidad: Demonio o fuerza disruptiva de la armonía.' },
  { id: 56, vocablo: 'Diocuinocho', fonetica: 'dio-cui-no-cho', significado: 'Cargo: Chamán de alto rango, mediador con lo invisible.' },
  { id: 57, vocablo: 'Taniti', fonetica: 'ta-ni-ti', significado: 'Cargo: Chamán o sabio local de la banda.' },
  { id: 58, vocablo: 'Chirigaki', fonetica: 'chi-ri-ga-ki', significado: 'Topónimo: Misión de San Luis Gonzaga, sitio de memoria.' },
  { id: 59, vocablo: 'Conchó', fonetica: 'con-cho', significado: 'Topónimo: Loreto. Significa "mangle rojo" en la antigua lengua.' },
  { id: 60, vocablo: 'Tshukíti', fonetica: 'tshu-ki-ti', significado: 'Concepto: Ido arriba, trascendencia tras la muerte.' },
];
